issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:easy-octo/apprentice-hire-exercise:ref:refs/heads/master
claim_pattern:
  workflow_ref: easy-octo/apprentice-hire-exercise/.github/workflows/release-please.yaml@.* # Still not sure what needs to come after the actual workflow name but this works

permissions:
  contents: write
  pull_requests: write
