name: Test, Build, and Push Docker image

on:
  # Runs on pushes targeting the default branch
  push:
    tags: ["v*"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t apprentice-exercise

      - name: Spin up container
        run: docker run -dp 172.17.0.1:80:80 apprentice-exercise

      - name: Run tests
        id: testing
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        if: steps.testing.outcome == 'success'
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/apprentice-exercise:${{ steps.get_version.outputs.VERSION }}"
          docker tag apprentice-exercise $IMAGE_NAME
          docker push $IMAGE_NAME
